### ISSUE TITLE
uSync with Umbraco CMS v7.2.5

### ISSUE THREAD

**Issue by croban** [KevinJump/jumps.umbraco.usync#38]
I have this error if Document type (XML) have been changed.

2015-05-19 15:48:00,873 [44] ERROR jumps.umbraco.usync.SyncDocType - [Thread 43] Failed to import Myfirstdt
System.NullReferenceException: Object reference not set to an instance of an object.
   at Umbraco.Core.Services.PackagingService.<>c__DisplayClass1e.<UpdateContentTypeFromXml>b__1d()
   at System.Lazy`1.CreateValue()
   at System.Lazy`1.LazyInitValue()
   at System.Lazy`1.get_Value()
   at Umbraco.Core.Models.ContentTypeBase.get_ParentId()
   at Umbraco.Core.Persistence.Factories.ContentTypeFactory.BuildNodeDto(IContentType entity)
   at Umbraco.Core.Persistence.Factories.ContentTypeFactory.BuildContentTypeDto(IContentType entity)
   at Umbraco.Core.Persistence.Factories.ContentTypeFactory.BuildDto(IContentType entity)
   at Umbraco.Core.Persistence.Repositories.ContentTypeRepository.PersistUpdatedItem(IContentType entity)
   at Umbraco.Core.Persistence.Repositories.RepositoryBase`2.PersistUpdatedItem(IEntity entity)
   at Umbraco.Core.Persistence.UnitOfWork.PetaPocoUnitOfWork.Commit(Action`1 transactionCompleting)
   at Umbraco.Core.Persistence.UnitOfWork.PetaPocoUnitOfWork.Commit()
   at Umbraco.Core.Services.ContentTypeService.Save(IEnumerable`1 contentTypes, Int32 userId)
   at Umbraco.Core.Services.PackagingService.ImportContentTypes(XElement element, Boolean importStructure, Int32 userId, Boolean raiseEvents)
   at jumps.umbraco.usync.Extensions.IContentTypeExtensions.ImportContentType(XElement node)

XML (mysecondproperty is added):
```xml
<?xml version="1.0" encoding="utf-16"?>
<DocumentType>
  <Info>
    <Name>Myfirstdt</Name>
    <Alias>Myfirstdt</Alias>
    <Icon>.sprTreeFolder</Icon>
    <Thumbnail>folder.png</Thumbnail>
    <Description />
    <AllowAtRoot>True</AllowAtRoot>
    <Master />
    <AllowedTemplates>
      <Template>MyFirstDT</Template>
    </AllowedTemplates>
    <DefaultTemplate>MyFirstDT</DefaultTemplate>
  </Info>
  <Structure />
  <GenericProperties>
    <GenericProperty>
      <Name>Myfirstproperty</Name>
      <Alias>myfirstproperty</Alias>
      <Type>Umbraco.Textbox</Type>
      <Definition>0cc0eba1-9960-42c9-bf9b-60e150b429ae</Definition>
      <Tab />
      <Mandatory>False</Mandatory>
      <Validation />
      <Description><![CDATA[this is first description]]></Description>
    </GenericProperty>
    <GenericProperty>
      <Name>Mysecodondproperty</Name>
      <Alias>mysecodondproperty</Alias>
      <Type>Umbraco.Textbox</Type>
      <Definition>0cc0eba1-9960-42c9-bf9b-60e150b429ae</Definition>
      <Tab />
      <Mandatory>False</Mandatory>
      <Validation />
      <Description><![CDATA[this is first description]]></Description>
    </GenericProperty>
  </GenericProperties>
  <Tabs />
</DocumentType>
```

**Comment by croban** [comment]
update from 2.5 to 3.1 solved this problem
